# Generated by Django 5.0.3 on 2024-04-24 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yariapp', '0002_categorystay_payment_baby_sittersform'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Baby',
            new_name='Babyform',
        ),
    ]
