# Generated by Django 5.0.3 on 2024-04-24 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yariapp', '0003_rename_baby_babyform'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='paid_by',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='sittersform',
            name='date_of_birth',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
