# Generated by Django 5.0.3 on 2024-04-26 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yariapp', '0005_depatureform_ondutyform_delete_visitor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arrivalform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_name', models.CharField(blank=True, max_length=50)),
                ('parent_name', models.CharField(blank=True, max_length=50)),
                ('timeInDay', models.DateField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('brought_by', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Baby_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_name', models.CharField(blank=True, max_length=50)),
                ('parent_name', models.CharField(blank=True, max_length=50)),
                ('Baby_no', models.IntegerField(blank=True, null=True)),
                ('Age', models.IntegerField(blank=True, null=True)),
                ('Gender', models.IntegerField(null=True)),
                ('Date_birth', models.DateField(null=True)),
                ('Date_registration', models.DateField(null=True)),
                ('Location', models.IntegerField(null=True)),
                ('Fee', models.IntegerField(blank=True, null=True)),
                ('Arrival_Time', models.IntegerField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='sittersform',
            name='timein',
        ),
        migrations.RemoveField(
            model_name='sittersform',
            name='timeout',
        ),
        migrations.AddField(
            model_name='babyform',
            name='baby_no',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
