# Generated by Django 5.0.3 on 2024-04-26 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yariapp', '0007_alter_baby_list_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baby_list',
            name='Location',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
