# Generated by Django 5.0.3 on 2024-04-26 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yariapp', '0009_alter_baby_list_arrival_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baby_list',
            name='Arrival_Time',
            field=models.DateTimeField(null=True),
        ),
    ]
