# Generated by Django 5.0.3 on 2024-04-27 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yariapp', '0010_alter_baby_list_arrival_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Baby_list',
        ),
        migrations.RemoveField(
            model_name='babyform',
            name='c_fee',
        ),
        migrations.RemoveField(
            model_name='depatureform',
            name='timeInDay',
        ),
        migrations.RemoveField(
            model_name='sittersform',
            name='c_fee',
        ),
    ]
