# Generated by Django 5.0.3 on 2024-04-27 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yariapp', '0011_delete_baby_list_remove_babyform_c_fee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='babyform',
            name='timeInDay',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='babyform',
            name='timeOutDay',
            field=models.TimeField(),
        ),
    ]
