# Generated by Django 5.0.3 on 2024-04-29 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yariapp', '0013_alter_babyform_timeinday_alter_babyform_timeoutday'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Payment',
            new_name='Paymentform',
        ),
    ]
