# Generated by Django 5.0.3 on 2024-04-29 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yariapp', '0014_rename_payment_paymentform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='babyform',
            name='timeInDay',
        ),
        migrations.RemoveField(
            model_name='babyform',
            name='timeOutDay',
        ),
        migrations.AddField(
            model_name='paymentform',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='arrivalform',
            name='timeInDay',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='depatureform',
            name='timeOutDay',
            field=models.DateTimeField(),
        ),
    ]
