# Generated by Django 5.0.3 on 2024-04-29 11:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yariapp', '0015_remove_babyform_timeinday_remove_babyform_timeoutday_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='babyform',
            name='timeInDay',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
