# Generated by Django 5.0.3 on 2024-04-29 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yariapp', '0016_babyform_timeinday'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payno', models.IntegerField(blank=True, null=True)),
                ('sitter_name', models.CharField(max_length=10)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('currency', models.CharField(blank=True, default='Ugx', max_length=10, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('c_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='yariapp.categorystay')),
            ],
        ),
    ]
