# Generated by Django 5.0.3 on 2024-05-03 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yariapp', '0018_loginform'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(blank=True, max_length=50)),
                ('amount', models.CharField(blank=True, max_length=50)),
                ('quantity', models.IntegerField(blank=True, max_length=50)),
                ('total_price', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Shopform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_name', models.CharField(blank=True, max_length=50)),
                ('doll_name', models.CharField(blank=True, max_length=50)),
                ('quality', models.CharField(blank=True, max_length=50)),
                ('brand', models.CharField(blank=True, max_length=50)),
                ('buying_price', models.CharField(blank=True, max_length=50)),
                ('selling_price', models.CharField(blank=True, max_length=50)),
                ('total_price', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='loginForm',
        ),
    ]
