# Generated by Django 5.0.3 on 2024-05-03 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yariapp', '0019_proform_shopform_delete_loginform'),
    ]

    operations = [
        migrations.AddField(
            model_name='proform',
            name='unit',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='proform',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
    ]
