# Generated by Django 5.0.3 on 2024-05-03 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yariapp', '0020_proform_unit_alter_proform_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proform',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10),
        ),
    ]
