# Generated by Django 5.0.3 on 2024-05-03 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yariapp', '0022_alter_ondutyform_telephone_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ondutyform',
            name='telephone_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
