# Generated by Django 5.0.3 on 2024-05-04 16:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yariapp', '0024_alter_sittersform_telephone_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arrivalform',
            name='timeInDay',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='depatureform',
            name='timeOutDay',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='sittersform',
            name='date_of_birth',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
