# Generated by Django 5.0.3 on 2024-05-08 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yariapp', '0027_sitter_delete_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payform',
            name='c_payment',
        ),
    ]
