# Generated by Django 5.0.3 on 2024-05-08 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yariapp', '0029_remove_paymentform_c_payment_paymentform_baby_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='ondutyform',
            name='sitter_assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='yariapp.sittersform'),
        ),
        migrations.AlterField(
            model_name='babyform',
            name='baby_no',
            field=models.IntegerField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='ondutyform',
            name='baby_assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='yariapp.arrivalform'),
        ),
        migrations.AlterField(
            model_name='payform',
            name='payno',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='paymentform',
            name='payno',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
