# Generated by Django 5.0.3 on 2024-05-08 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yariapp', '0030_ondutyform_sitter_assigned_to_alter_babyform_baby_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='babyform',
            name='baby_no',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
