# Generated by Django 5.0.3 on 2024-05-08 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yariapp', '0032_remove_babyform_baby_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='babyform',
            name='baby_no',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
