# Generated by Django 5.0.3 on 2024-05-09 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yariapp', '0033_babyform_baby_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='babyform',
            name='baby_no',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
