# Generated by Django 5.0.3 on 2024-05-11 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yariapp', '0036_remove_babyform_baby_no_remove_paymentform_payno'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Supplier',
        ),
        migrations.RemoveField(
            model_name='ondutyform',
            name='sitter_assigned_to',
        ),
    ]
