# Generated by Django 5.0.3 on 2024-05-11 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yariapp', '0037_delete_supplier_remove_ondutyform_sitter_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='ondutyform',
            name='sitter_assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='yariapp.sittersform'),
        ),
    ]
