# Generated by Django 5.0.3 on 2024-05-13 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yariapp', '0038_ondutyform_sitter_assigned_to'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arrivalform',
            old_name='b_name',
            new_name='Baby_name',
        ),
        migrations.RenameField(
            model_name='babyform',
            old_name='b_name',
            new_name='Baby_name',
        ),
        migrations.RenameField(
            model_name='babyform',
            old_name='c_stay',
            new_name='catergory_stay',
        ),
        migrations.RenameField(
            model_name='depatureform',
            old_name='b_name',
            new_name='Baby_name',
        ),
        migrations.RenameField(
            model_name='shopform',
            old_name='b_name',
            new_name='Baby_name',
        ),
        migrations.RenameField(
            model_name='sittersform',
            old_name='c_stay',
            new_name='catergory_stay',
        ),
        migrations.RenameField(
            model_name='sittersform',
            old_name='s_name',
            new_name='sitter_name',
        ),
        migrations.RemoveField(
            model_name='payform',
            name='payno',
        ),
        migrations.AddField(
            model_name='payform',
            name='baby_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payform',
            name='total_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payform',
            name='amount',
            field=models.IntegerField(blank=True, default=3000, null=True),
        ),
    ]
