# Generated by Django 5.0.3 on 2024-05-13 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yariapp', '0039_rename_b_name_arrivalform_baby_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arrivalform',
            old_name='Baby_name',
            new_name='b_name',
        ),
        migrations.RenameField(
            model_name='babyform',
            old_name='catergory_stay',
            new_name='c_stay',
        ),
        migrations.RenameField(
            model_name='depatureform',
            old_name='Baby_name',
            new_name='b_name',
        ),
        migrations.RenameField(
            model_name='payform',
            old_name='sitter_name',
            new_name='s_name',
        ),
        migrations.RenameField(
            model_name='paymentform',
            old_name='Baby_name',
            new_name='b_name',
        ),
        migrations.RenameField(
            model_name='shopform',
            old_name='Baby_name',
            new_name='b_name',
        ),
        migrations.RenameField(
            model_name='sittersform',
            old_name='catergory_stay',
            new_name='c_stay',
        ),
    ]
