# Generated by Django 5.0.3 on 2024-05-13 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yariapp', '0041_remove_ondutyform_sitter_assigned_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payform',
            name='s_name',
            field=models.CharField(max_length=50),
        ),
    ]
