# Generated by Django 5.0.3 on 2024-05-13 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yariapp', '0042_alter_payform_s_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentform',
            name='b_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
