# Generated by Django 5.0.3 on 2024-05-13 19:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yariapp', '0043_alter_paymentform_b_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='babyform',
            name='Baby_name',
        ),
        migrations.RemoveField(
            model_name='payform',
            name='total_amount',
        ),
        migrations.AddField(
            model_name='babyform',
            name='b_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='arrivalform',
            name='b_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='arrivalform',
            name='brought_by',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='arrivalform',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='arrivalform',
            name='parent_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='babyform',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='babyform',
            name='c_stay',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='yariapp.categorystay'),
        ),
        migrations.AlterField(
            model_name='babyform',
            name='gender',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='babyform',
            name='location',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='babyform',
            name='sponsorname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='depatureform',
            name='b_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='depatureform',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='depatureform',
            name='parent_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='depatureform',
            name='person_pickingup',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ondutyform',
            name='baby_assigned_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='yariapp.arrivalform'),
        ),
        migrations.AlterField(
            model_name='ondutyform',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ondutyform',
            name='telephone_no',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='payform',
            name='amount',
            field=models.IntegerField(default=3000),
        ),
        migrations.AlterField(
            model_name='payform',
            name='baby_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='payform',
            name='currency',
            field=models.CharField(default='Ugx', max_length=10),
        ),
        migrations.AlterField(
            model_name='payform',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='payform',
            name='s_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='paymentform',
            name='b_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='paymentform',
            name='currency',
            field=models.CharField(default='Ugx', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='paymentform',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='paymentform',
            name='paid_by',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='proform',
            name='amount',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='proform',
            name='item_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='proform',
            name='quantity',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='proform',
            name='total_price',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='proform',
            name='unit',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='shopform',
            name='b_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='shopform',
            name='brand',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='shopform',
            name='buying_price',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='shopform',
            name='doll_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='shopform',
            name='quality',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='shopform',
            name='selling_price',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='shopform',
            name='total_price',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sittersform',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sittersform',
            name='c_stay',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='yariapp.categorystay'),
        ),
        migrations.AlterField(
            model_name='sittersform',
            name='gender',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sittersform',
            name='level_of_education',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sittersform',
            name='location',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sittersform',
            name='next_of_kin',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sittersform',
            name='sitter_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sittersform',
            name='telephone_no',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
