# Generated by Django 5.0.3 on 2024-05-14 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yariapp', '0045_remove_shopform_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopform',
            name='total_price',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
