# Generated by Django 5.0.3 on 2024-05-14 07:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yariapp', '0046_shopform_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopform',
            name='order_date',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
    ]
