# Generated by Django 5.0.3 on 2024-05-14 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yariapp', '0047_shopform_order_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopform',
            name='b_name',
        ),
        migrations.CreateModel(
            name='Sellingform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sold_date', models.DateField(auto_now_add=True)),
                ('doll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yariapp.sellingform')),
            ],
        ),
    ]
